### PR TITLE
Create PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by jcbhmr**
This PR would...
- [x] Add a cutsey "Thanks for contributing! ❤️" `<!-- -->` comment to the user-wide `PULL_REQUEST_TEMPLATE.md`

This is just something that's only goal is to make someone smile when they open a PR against your repository. 😊

Don't worry! You can always override this at a per-repo level just like always.

### CODE REVIEW

**Comment by jcbhmr** [comment]
@jimmywarting Just a heads up that it doesn't appear as though you are watching this repo 😜

image

**Comment by jimmywarting** [comment]
Thank you. I have been thinking of taking that PR template from my own [fetch-blob](https://raw.githubusercontent.com/node-fetch/fetch-blob/main/.github/PULL_REQUEST_TEMPLATE.md)

it's more general purpose, and i think it would work for most projects. 
(think the same one is also used on `node-fetch`)

don't want it to be too verbose, ppl creating PR/issues do not want to read all of it and feel like they have to fill in a total 10 pages application form...

think i might want to try out this yml format that's more like a template/form that they fill in instead.
have been reading up on https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

but i will use this for now. better than nothing.

**Comment by jimmywarting** [comment]
I just started following 😉

**Comment by jcbhmr** [comment]
Here's a PULL_REQUEST_TEMPLATE.md from someone else that I helped write: https://github.com/Andrew-Chen-Wang/.github/blob/master/PULL_REQUEST_TEMPLATE.md?plain=1

image
If I were to rewrite it, I might use "I" instead of "we" 🤷‍♂️ I'd also try to make it shorter 😁

You could use something like that: casual enough for simple repos but also answers the "what do I write in this textbox" question.

**Pull request merged**
